CAR PRICE CLASSIFICATION

In [6]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler 
import torch

Assigning Features and Labels

In [7]:
dataset = pd.read_csv("C:/Users/hp/Desktop/pandas/CarPrice.csv")
dataset = dataset.drop(["car_ID","CarName"], axis=1).dropna()
dataset["price"] = dataset["price"]/10000
label = dataset["price"]
feature = dataset.drop("price",axis=1)
feature = pd.get_dummies(feature)

In [8]:
features = np.array(feature)
labels = np.array(label).reshape(-1,1)
features = StandardScaler().fit_transform(features)
features = torch.tensor(features, dtype = torch.float32)
labels = torch.tensor(labels,dtype = torch.float32)

In [9]:
model = torch.nn.Linear(52,1)
preds=model(features)

Predicting the Weight and Bias

In [10]:
from torch.nn.functional import mse_loss

loss  = mse_loss(preds, labels)
print(loss)

loss.backward()

print(model.weight.grad)
print(model.bias.grad)

tensor(3.2981, grad_fn=<MseLossBackward0>)
tensor([[ 0.2058, -1.4076, -1.7946, -1.8881, -0.3867, -2.1350, -2.1353, -1.6654,
          0.1618,  0.1166, -2.0390,  0.2956,  1.9672,  2.0101, -0.0129,  0.0129,
          0.4947, -0.4947, -0.1617,  0.1617, -0.7083, -0.5721,  0.7932, -0.2660,
         -0.0405, -0.3599,  1.6574, -1.5379,  0.7887, -0.7887, -0.3804, -0.3687,
         -0.0716,  1.0673, -0.3822, -1.0359,  0.0404, -1.3208, -0.6440,  1.4889,
         -0.8730,  0.5133, -0.4732,  0.0404,  0.6090,  1.2392,  0.0778, -0.0129,
          0.0174, -1.4769,  0.0210,  0.1239]])
tensor([-2.5980])


In [11]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

optimizer.step()
optimizer.zero_grad()

preds = model(features)
loss = mse_loss(preds, labels)
print(loss)

tensor(3.2379, grad_fn=<MseLossBackward0>)


Training Loop

In [12]:
epochs = 15000
for epoch in range(epochs):
    preds = model(features)
    loss = mse_loss(preds, labels)
    
    if (epoch+1)%1000 == 0:
        print(loss)

    loss.backward()
    
    optimizer.step()
    optimizer.zero_grad()

tensor(0.0936, grad_fn=<MseLossBackward0>)
tensor(0.0526, grad_fn=<MseLossBackward0>)
tensor(0.0482, grad_fn=<MseLossBackward0>)
tensor(0.0459, grad_fn=<MseLossBackward0>)
tensor(0.0444, grad_fn=<MseLossBackward0>)
tensor(0.0433, grad_fn=<MseLossBackward0>)
tensor(0.0425, grad_fn=<MseLossBackward0>)
tensor(0.0418, grad_fn=<MseLossBackward0>)
tensor(0.0413, grad_fn=<MseLossBackward0>)
tensor(0.0410, grad_fn=<MseLossBackward0>)
tensor(0.0407, grad_fn=<MseLossBackward0>)
tensor(0.0404, grad_fn=<MseLossBackward0>)
tensor(0.0402, grad_fn=<MseLossBackward0>)
tensor(0.0400, grad_fn=<MseLossBackward0>)
tensor(0.0399, grad_fn=<MseLossBackward0>)


Result

In [13]:
x = 87
preds = model(features[x])
print(preds*10000,labels[x]*10000)

tensor([10404.7832], grad_fn=<MulBackward0>) tensor([9279.])
