In [1]:
import pandas as pd
import numpy as np
import torch
from sklearn.preprocessing import StandardScaler
from torch.nn.functional import mse_loss

In [3]:
dataset = pd.read_csv("C:/Users/hp/Desktop/pandas/Mobile dataset.csv")
dataset = dataset.drop(["model","base_color","processor"], axis=1)
dataset["battery_capacity"] = dataset["battery_capacity"]/1000
dataset["num_of_ratings"] = dataset["num_of_ratings"]/10000
dataset["sales_price"] = dataset["sales_price"]/1000
dataset["ROM"] = dataset["ROM"]/100
label = dataset["sales"]
feature = dataset.drop("sales",axis=1)
feature = pd.get_dummies(feature)

In [4]:
features = np.array(feature)
labels = np.array(label).reshape(-1,1)
features = StandardScaler().fit_transform(features)
features = torch.tensor(features, dtype = torch.float32)
labels = torch.tensor(labels,dtype = torch.float32)
print(features.shape, labels.shape)
print(features)

torch.Size([430, 20]) torch.Size([430, 1])
tensor([[-0.6617, -1.5233, -4.5237,  ..., -0.2930, -0.0969, 10.3199],
        [-0.6617, -0.6059, -2.6272,  ...,  3.4128, -0.0969, -0.0969],
        [-0.6617, -1.5233, -4.5237,  ..., -0.2930, -0.0969, 10.3199],
        ...,
        [ 0.3527,  0.3115,  0.3528,  ..., -0.2930, -0.0969, -0.0969],
        [-1.1689, -1.0646, -0.4599,  ..., -0.2930, -0.0969, -0.0969],
        [-1.1689, -1.0646, -1.5436,  ...,  3.4128, -0.0969, -0.0969]])


In [5]:
model = torch.nn.Sequential(
    torch.nn.Linear(20,10),
    torch.nn.LeakyReLU(), # activation functions
    torch.nn.Linear(10,6),
    torch.nn.ReLU(),
    torch.nn.Linear(6,9),
    torch.nn.ReLU(),
    torch.nn.Linear(9,1)
)

preds = model(features)
print(preds.shape)

print(preds)

torch.Size([430, 1])
tensor([[-0.2453],
        [-0.2508],
        [-0.2453],
        [-0.2507],
        [-0.2519],
        [-0.2526],
        [-0.2519],
        [-0.2526],
        [-0.2519],
        [-0.2519],
        [-0.2508],
        [-0.2519],
        [-0.2500],
        [-0.2486],
        [-0.2500],
        [-0.2501],
        [-0.2526],
        [-0.2526],
        [-0.2508],
        [-0.2486],
        [-0.2485],
        [-0.2501],
        [-0.2486],
        [-0.2526],
        [-0.2501],
        [-0.2501],
        [-0.2486],
        [-0.2507],
        [-0.2508],
        [-0.2501],
        [-0.2508],
        [-0.2500],
        [-0.2539],
        [-0.2507],
        [-0.2485],
        [-0.2453],
        [-0.2485],
        [-0.2485],
        [-0.2500],
        [-0.2485],
        [-0.2500],
        [-0.2485],
        [-0.2434],
        [-0.2520],
        [-0.2501],
        [-0.2501],
        [-0.2501],
        [-0.2507],
        [-0.2507],
        [-0.2507],
        [-0.2507],
        [-

In [6]:
loss = mse_loss(preds, labels)
loss

tensor(4302.6167, grad_fn=<MseLossBackward0>)

In [7]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

In [8]:
epochs = 15000
for epoch in range(epochs):
    preds = model(features)
    loss = mse_loss(preds, labels)
    
    if (epoch+1)%(epochs//10) == 0:
        print(loss)

    loss.backward()
    
    optimizer.step()
    optimizer.zero_grad()

tensor(55.1989, grad_fn=<MseLossBackward0>)
tensor(13.8363, grad_fn=<MseLossBackward0>)
tensor(7.7278, grad_fn=<MseLossBackward0>)
tensor(7.4039, grad_fn=<MseLossBackward0>)
tensor(6.1639, grad_fn=<MseLossBackward0>)
tensor(5.5631, grad_fn=<MseLossBackward0>)
tensor(4.9717, grad_fn=<MseLossBackward0>)
tensor(4.2947, grad_fn=<MseLossBackward0>)
tensor(4.0836, grad_fn=<MseLossBackward0>)
tensor(3.6920, grad_fn=<MseLossBackward0>)


In [9]:
x = 100
preds = model(features[x])
print(preds,labels[x])

tensor([49.3180], grad_fn=<AddBackward0>) tensor([50.0400])
